// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://koasdsillrwcejhsywdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvYXNkc2lsbHJ3Y2VqaHN5d2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NTIxODMsImV4cCI6MjA3NDMyODE4M30.0treaJNaXxuZTkxols0CunnPfx4mf-xPcRBQLa5KRj0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});